version: "3"
services:

  postgres:
    image: postgres:latest
    container_name: pdexample
    ports:
      - 5433:5432 # postgres is set up on 5432 but exposed on 5433
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres

    logging:
      options:
        max-size: 10m
        max-file: "3"

    volumes:
#      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
